% ZEMAX DDE Server Toolbox
%
% ZEMAX DDE Server Toolbox Version 2
% Provides access to ZEMAX functionality from Matlab.
% NOTE : The ZEMAX DDE server maintains an independent copy of the lens from the Lens Data Editor (LDE).
%        See zPushLens and zGetRefresh for moving lens data between the DDE server and the LDE.
% For further details, see the chapter on "ZEMAX Extensions" in the ZEMAX manual.
%
% Before calling any functions that access the ZEMAX DDE server, it is necessary to initialise the DDE link
% using the zDDEInit function. Failure to do so will cause Matlab to issue a verbose yet completely
% uninformative error message.
%
%
%   This toolbox is free software; you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation; either version 2 of the License, or
%   (at your option) any later version.
%
%   This toolbox is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License (in the file COPYING) for more details.
%
% Report bugs and updates to dgriffith@csir.co.za
%
% List of Functions - Function names are case insensitive.
%   ACCOSin                 - ACCOS LENO format importer for ZEMAX.
%   BIMwrite                - Write ZEMAX format binary greyscale image.
%   Census                  - Provides a listing of all functions in this toolbox, along with current revisions.
%   deg2rad                 - Converts degrees to radians.
%   digitize                - A script to digitize data from an image of a graph. Author J. Cogdell. Not MZDDE. 
%   LSF                     - Diffraction-limited Monochromatic Line Spread Function.
%   PLSF                    - Diffraction-limited Polychromatic Line Spread Function.
%   MTF                     - Diffraction-limited Monochromatic Modulation Transfer Function.
%   PMTF                    - Diffraction-limited Polychromatic Modulation Transfer Function.
%   Planck                  - Planck black body function.
%   PlotZemaxOTF            - Plot a thru-frequency MTF/OTF as returned by ReadZemaxOTF or zGetMTF.
%   PSF                     - Diffraction-limited Monochromatic Point Spread Function.
%   PPSF                    - Diffraction-limited Polychromatic Point Spread Function.
%   PSF2D                   - 2D Image of the Diffraction-limited Polychromatic Point Spread Function.
%   rad2deg                 - Converts radians to degrees.
%   RayDevParPlate          - Computes lateral deviation of a ray passing through a plane parallel plate.
%   ReadCIE                 - Read CIE data into workspace variables (colour observers, daylight etc.)
%   ReadZemaxGImAnal        - Reads data from a ZEMAX Geometric Image Analysis text data file.
%   ReadZemaxIllum          - Reads data from a ZEMAX Uniformity of Illumination Analysis test file.
%   ReadZemaxOTF            - Reads data from a OTF/MTF text file from ZEMAX (thru-frequency, thru-focus or thru-field).
%   ReadZemaxRMS            - Reads data from a ZEMAX RMS Analysis - Spot Size, Wavefront or Strehl Ratio.
%   ReadZemaxVignet         - Reads data from a ZEMAX Vignetting Analysis text file.
%   ReadZemaxWaveMap        - Reads data from a Wave Map text data file generated by ZEMAX.
%   SpiralSpot              - Compute image plane trajectory of a ray scanned in a spiral over the pupil.
%   NarcWiz                 - A wizard for performing narcissus analysis on staring infrared cameras.
%   n_air                   - Refractive index of air over wavelength, temperature and pressure.
%   DoublePass              - Put a lens system into double pass.
%   genRayDataMode0         - Generate grid of ray data ready for zArrayTrace mode 0.
%   gridXYRayData           - Generate basic grid of ray data for zArrayTrace.
%   IntSphere               - Compute the spectral radiance of an integrating sphere given input spectral flux.
%   Onion                   - Split lens into layers for analysis of axial temperature gradients.
%   SagEvenAsphere          - Computes the sag of a standard ZEMAX even aspheric surface.
%   WriteZemaxWaveFile      - Write a list of wavelengths and weights in ZEMAX .wav file format.
%   zArrayTrace             - Performs tracing of large numbers of rays in ZEMAX.
%   zDDEBusy                - Checks to see if the ZEMAX DDE server is busy.
%   zDDEClose               - Close DDE communications channel to ZEMAX.
%   zDDEInit                - Open communications channel to ZEMAX DDE server.
%   zDDEStart               - Attempt zDDEInit. If no ZEMAX running, attempt to start ZEMAX.
%   zDeleteSurface          - Delete a lens surface.
%   zExportCAD              - Export lens CAD data (IGES, STEP, SAT) to a file.  
%   zExportCheck            - Check if lens CAD export has completed.
%   zFindLabel              - Find integer label attached to a lens surface using zSetLabel.
%   zFixSurfaceData         - Set lens surface data to 'fixed' mode.
%   zFixAllSurfaceData      - Set all lens surface data to 'fixed' mode.
%   zGetAddress             - Get address line in Preferences/Address.
%   zGetAspect              - Get the aspect ratio of ZEMAX graphics or print windows.
%   zGetBuffer              - Get DDE client specific data from a ZEMAX window being updated.
%   zGetCoatings            - Get a list of available coatings from the ZEMAX COATINGS.DAT file.
%   zGetConfig              - Get current lens configuration, number of configurations and configuration operands.
%   zGetDate                - Get current date from ZEMAX DDE server.
%   zGetExtra               - Get single extra data value from ZEMAX DDE server.
%   zGetField               - Get data on lens field points.
%   zGetFile                - Get the filename of the currently loaded lens.
%   zGetFirst               - Get first order data about the lens.
%   zGetGlass               - Get data on a glass at a particular lens surface.
%   zGetGlassCats           - Get a list of available text glass catalogues from the ZEMAX Glasscat directory.
%   zGetGlobalMatrix        - Get transformation matrix from local surface coordinates to global lens coordinates.
%   zGetIndex               - Get index of refraction data at a lens surface.
%   zGetLabel               - Retrieve integer label associated with a surface.
%   zGetMetaFile            - Create Windows Metafile of a ZEMAX graphic analysis window.
%   zuiGetMetaFile          - As for zGetMetaFile, but with Save As dialog box.
%   zGetMulticon            - Get data from the ZEMAX multi-configuration editor.
%   zGetMTF                 - Get MTF computation from ZEMAX for current lens. Returns as for ReadZemaxOTF function.
%   zGetName                - Get the name of the lens in ZEMAX.
%   zGetNSCData             - Get number of NSC objects.
%   zGetNSCObjectData       - Get data describing NSC objects in ZEMAX.
%   zGetNSCPosition         - Get position data for an NSC object in ZEMAX.
%   zGetNSCParameter        - Get numeric parameters associated with an NSC object in ZEMAX.
%   zGetNSCSettings         - Get ZEMAX settings affecting raytracing in non-sequential components.
%   zGetOperand             - Get data from the ZEMAX Merit Function editor.
%   zGetOperandMatrix       - Get the entire merit function matrix from the Merit Function Editor.
%   zGetPath                - Get the path for the ZEMAX installation directory and lens directory.
%   zGetPolState            - Get the default polarization state from ZEMAX.
%   zGetPupil               - Get data on the aperture stop and pupils.
%   zGetPolTrace            - Perform a full polarization raytrace through the ZEMAX lens.
%   zGetPolTraceDirect      - Direct access full polarization raytrace.
%   zGetRefresh             - Copies the lens in the Lens Data Editor (LDE) into the ZEMAX DDE server.
%   zGetSag                 - Get the sag at particular x and y coordinates on a lens surface.
%   zGetSequence            - Get the sequence numbers of the lenses in the DDE server and LDE.
%   zGetSerial              - Get the ZEMAX hardware lock serial number.
%   zGetSolve               - Get data on solves and pickups on lens surfaces.
%   zGetSurfaceData         - Get a data item describing a lens surface.
%   zsGetSurfaceData        - Get data for a lens surface in a Matlab structure.
%   zsGetSurfaceDataVector  - Get all basic surface data in a vector of Matlab structures.
%   zGetSurfaceDLL          - Get the name of a DLL for user-defined surface types.
%   zGetSurfaceParameter    - Get single surface parameter datum.
%   zGetSurfaceParamVector  - Get vector of all parameter values at a surface.
%   zGetSystem              - Get general information on the lens system in the ZEMAX DDE server.
%   zsGetSystem             - Get general lens information in a Matlab structure.
%   zGetSystemAper          - Get lens system aperture data.
%   zGetTextFile            - Save text from any ZEMAX analysis window which supports text.
%   zGetTimeout             - Get the timeout value in seconds for ZEMAX DDE calls.
%   zGetTol                 - Get data on a tolerance operand in the ZEMAX tolerance editor.
%   zGetTolCount            - Get the number of current lens tolerance operands from ZEMAX.
%   zGetTolMatrix           - Get a matrix of all current lens tolerances.
%   zGetTrace               - Trace a ray through the current lens in the ZEMAX DDE server.
%   zGetTraceDirect         - Direct access raytrace through the current lens in the ZEMAX DDE server.
%   zGetUpdate              - Perform update on the current lens in the ZEMAX DDE server.
%   zGetVersion             - Get the ZEMAX version which is running.
%   zGetWave                - Get data on a currently defined wavelength in ZEMAX.
%   zGetWaveMatrix          - Get all data on wavelengths in a matrix.
%   zImportExtraData        - Import extra data to a ZEMAX surface which needs it e.g. Grid Sag.
%   zuiImportExtraData      - As for zImportExtraData, but with File Open dialog box.
%   zInsertSurface          - Insert a new surface in the lens.
%   zLoadFile               - Load a ZEMAX lens surface into the DDE server.
%   zuiLoadFile             - As for zLoadFile, except with File Open dialog.
%   zLoadMerit              - Load a merit function file from a .MF or .ZMX file.
%   zuiLoadMerit            - As for zLOadMerit, except that an Open File dialog is presented.
%   zMakeGraphicWindow      - Request ZEMAX to generate a graphic display from data stored in client generated file.
%   zMakeTextWindow         - Request ZEMAX to display text stored in a client generated file.
%   zNewLens                - Erase the lens in the ZEMAX DDE server.
%   zNumSurfs               - Returns the number of surfaces in the lens.
%   zOpenWindow             - Open a ZEMAX action/analysis window.
%   zOptimize               - Run the damped least squares on the lens in the ZEMAX DDE server.
%   zPushLens               - Copy the lens in the ZEMAX DDE server into the ZEMAX Lens Data Editor.
%   zReleaseWindow          - Release a window locked during ZEMAX-client interaction.
%   zSaveFile               - Save a lens file from the ZEMAX DDE server.
%   zuiSaveFile             - As for zSaveLens, only a Save As dialog is used.
%   zSetAperture            - Set aperture details on a lens surface.
%   zSetBuffer              - Write text to a buffer for ZEMAX-client interactions.
%   zSetConfig              - Change selected lens configuration.
%   zSetExtra               - Set extra data associated with a lens surface in the ZEMAX DDE server.
%   zSetField               - Set details of a field point in the lens.
%   zSetFieldType           - Set the type of field points and the total number of points.
%   zSetFieldMatrix         - Set field type and all field point data from a Matlab matrix.
%   zSetFloat               - Set all surface without apertures to have floating apertures.
%   zSetLabel               - Attach an integer label to a lens surface for later reference.
%   zSetMEMState            - Set the micro-mirror state of a MEMS digital mirror device (DMD/DLP)
%   zSetMulticon            - Set multi-configuration data for lens surfaces in ZEMAX.
%   zSetMulticonOp          - Set up operand types in the ZEMAX multi-configuration editor.
%   zSetNSCNull             - Sets range of objects at a non-sequential surface to the 'Null Object'.
%   zSetNSCObjectData       - Set basic data for an non-sequential object in ZEMAX.
%   zsSetNSCObject          - Set data for an NSC object or objects through use of a Matlab structure array.
%   zSetNSCPosition         - Set position and tilt of a non-sequential object in ZEMAX.
%   zSetNSCParameter        - Set a parameter associated with an NSC object in ZEMAX.
%   zSetNSCSettings         - Set global settings in ZEMAX related to handling of NSC ray tracing.
%   zSetOperand             - Set lens optimization operand in ZEMAX.
%   zSetPolState            - Set default polarization state for polarization raytracing in ZEMAX.
%   zSetSolve               - Set solves and pickups on lens surfaces.
%   zSetSurfaceData         - Set basic lens surface data in ZEMAX.
%   zSetSurfaceParameter    - Set a parameter associated with a lens surface in ZEMAX.
%   zSetSurfaceParamVector  - Set all parameters associated with a lens surface from a vector.
%   zSetSurfaceParamMatrix  - Set all parameters associated with all lens surfaces from a matrix.
%   zSetSystem              - Set global operating conditions for a lens system in ZEMAX.
%   zSetSystemAper          - Set aperture type and size for a lens in ZEMAX.
%   zSetTimeout             - Set the timeout for all ZEMAX DDE function calls.
%   zSetVig                 - Set vignetting factors automatically in ZEMAX.
%   zSetWave                - Set a wavelength and weight for the lens in ZEMAX.
%   zSetWaveMatrix          - Set all wavelengths and weights from a Matlab matrix.
%   zWindowMaximize         - Maximize a ZEMAX window.
%   zWindowMinimize         - Minimize a ZEMAX window.
%   zWindowRestore          - Restore a ZEMAX window to before a Maximize or Minimize.
%   ZemaxButtons            - Get a list of 3-letter codes for ZEMAX analysis and action windows (see zOpenWindow).
%   ZemaxOperands           - Get a list of ZEMAX optimization operands.
%

% MZDDE - The ZEMAX DDE Toolbox for Matlab.
% Copyright (C) 2002-2004 Defencetek, CSIR
% Contact : dgriffith@csir.co.za
% 
% This file is part of MZDDE.
% 
%  MZDDE is free software; you can redistribute it and/or modify
%  it under the terms of the GNU General Public License as published by
%  the Free Software Foundation; either version 2 of the License, or
%  (at your option) any later version.
%
%  MZDDE is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  GNU General Public License for more details.
%
%  You should have received a copy of the GNU General Public License
%  along with MZDDE (COPYING.html); if not, write to the Free Software
%  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%


% $Revision: 1.15 $
% $Author: dgriffith $
